Repository FuelLabs/data-systems, pull requests merged in 2024-07, with the labels that each got.

#37 feat(release): Publish Docker image
  .github/actions/docker-publish/action.yaml
  .github/workflows/docker_publish.yaml
Labels: #feat

#41 ci(repo): fix and improvements in release actions
  .github/actions/docker-publish/action.yaml
  .github/workflows/docker_publish.yaml
  .github/workflows/helm_publish.yaml
  .github/workflows/release.yaml
  .gitignore
Labels: #ci, s:repo

#47 feat(release): add helmchart statefulset
  helm/fuel-core-nats/Chart.yaml
  helm/fuel-core-nats/templates/statefulset.yaml
Labels: #feat

#50 feat(release): update working directory in dockerfile
  docker/fuel-core-nats.Dockerfile
Labels: #feat

#51 feat(release): add init container to statefulset
  docker/fuel-core-nats.Dockerfile
  helm/fuel-core-nats/Chart.yaml
  helm/fuel-core-nats/templates/statefulset.yaml
  helm/fuel-core-nats/values.yaml
Labels: #feat

#52 fix(release): misplaced end in helm chart
  helm/fuel-core-nats/templates/statefulset.yaml
Labels: #fix

#53 feat(release): bump chart version
  helm/fuel-core-nats/Chart.yaml
Labels: #feat

#54 fix(release): init containers volume mounts
  helm/fuel-core-nats/Chart.yaml
  helm/fuel-core-nats/templates/statefulset.yaml
Labels: #fix

#55 feat(release): init containers from helm release
  helm/fuel-core-nats/Chart.yaml
  helm/fuel-core-nats/templates/statefulset.yaml
Labels: #feat

#57 feat(release): disable pod health checks
  helm/fuel-core-nats/Chart.yaml
  helm/fuel-core-nats/values.yaml
Labels: #feat

#58 feat(release): bump app version
  helm/fuel-core-nats/Chart.yaml
Labels: #feat
